import fs from 'node:fs';
import type { StageName, PipelineRun, AgentsConfig } from './types.js';
import type { RunContext } from './run-context.js';
import type { InteractionHandler } from './interaction-handler.js';
import { GitHubInteractionHandler } from './github-interaction-handler.js';
import type { GitPlatformAdapter } from '../adapters/types.js';
import type { GitPublisher } from './git-publisher.js';
import { buildIssueBody, buildStageIssueTitle, buildSummaryIssueTitle } from './security.js';
import type { StageIssueParams } from './security.js';
import { extractManifestSummary } from './manifest.js';

export const AGENT_DESC: Record<StageName, string> = {
  intent_consultant: '意图深挖',
  researcher: '市场调研 & 竞品分析',
  product_owner: '产品需求文档',
  ux_designer: 'UX 流程 & 组件清单',
  api_designer: 'API 规范设计',
  ui_designer: 'React 组件 & 截图',
  tech_lead: '技术方案设计',
  coder: '代码生成',
  reviewer: '代码审查',
  validator: '交叉验证报告',
  qa_lead: 'QA 计划',
  tester: '自动化测试',
  security_auditor: '安全审计',
};

interface StageMetrics {
  startTime: number;
  hadClarification: boolean;
  wasRejected: boolean;
  commitSha?: string;
  clarificationQA?: { question: string; answer: string };
  rejectionFeedback?: string;
}

/**
 * Git and issue operations extracted from Orchestrator.
 * Handles stage commit, preview comments, stage/summary issues.
 */
export class OrchestratorGitOps {
  private stageIssues = new Map<string, number>();
  private stageMetrics = new Map<StageName, StageMetrics>();

  constructor(
    private ctx: RunContext,
    private agentsConfig: AgentsConfig,
    private handler: InteractionHandler,
    private adapter?: GitPlatformAdapter,
    private publisher?: GitPublisher,
  ) {}

  setPublisher(publisher: GitPublisher | undefined): void {
    this.publisher = publisher;
  }

  getStageIssues(): Map<string, number> {
    return new Map(this.stageIssues);
  }

  getRepoContext(): { owner: string; repo: string } {
    if (!this.adapter) return { owner: '', repo: '' };
    return { owner: this.adapter.getOwner(), repo: this.adapter.getRepo() };
  }

  /** Called by PipelineLoop onStageComplete callback. */
  async onStageComplete(stage: StageName, run: PipelineRun): Promise<void> {
    this.stageMetrics.set(stage, { startTime: Date.now(), hadClarification: false, wasRejected: false });
    await this.commitStageArtifacts(stage, run.id);
    const metrics = this.stageMetrics.get(stage);
    if (metrics && this.publisher) {
      metrics.commitSha = this.publisher.getLastCommitSha() ?? undefined;
    }
    await this.postPreviewComment(stage, run.id);
    try { await this.createStageIssue(stage, run); }
    catch (err) {
      this.ctx.logger.pipeline('warn', 'stage-issue:failed', {
        stage, error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  async askUserOnStageFail(stage: StageName, attempts: number, error: string): Promise<'retry' | 'skip' | 'abort'> {
    const agentName = AGENT_DESC[stage];
    const errorPreview = error.slice(0, 500);
    const answer = await this.handler.onClarification(
      stage,
      `${agentName}（${stage}）在自动重试 ${attempts} 次后仍然失败。\n\n错误信息:\n${errorPreview}\n\n请选择操作:`,
      '', [
        { label: 'Retry', description: '重置重试计数，重新执行该阶段' },
        { label: 'Skip', description: '跳过该阶段，继续后续流程' },
        { label: 'Abort', description: '终止 Pipeline' },
      ], false,
    );
    const lower = answer.toLowerCase();
    if (lower.includes('retry') || lower.includes('重试')) return 'retry';
    if (lower.includes('skip') || lower.includes('跳过')) return 'skip';
    return 'abort';
  }

  async createSummaryIssue(runId: string, instruction: string): Promise<void> {
    if (!this.adapter) return;
    const stageLinks = Array.from(this.stageIssues.entries())
      .filter(([key]) => key.startsWith(runId))
      .map(([key, num]) => {
        const stage = key.split(':')[1] as StageName;
        const name = this.agentsConfig.agents[stage]?.name ?? stage;
        const desc = AGENT_DESC[stage] ?? '';
        return `- **${name}** ${desc} — #${num}`;
      }).join('\n');
    const prRef = this.publisher?.getPR();
    const prLine = prRef ? `\n**PR:** #${prRef.number}` : '';
    await this.adapter.createIssue({
      title: buildSummaryIssueTitle(instruction),
      body: `## Pipeline Summary\n\n**Run:** \`${runId}\`${prLine}\n**Instruction:** ${instruction}\n\n### Stages\n${stageLinks}\n\n---\n_Generated by [Mosaicat](https://github.com/ZB-ur/mosaicat) pipeline_`,
      labels: ['pipeline:summary'],
    });
  }

  // --- Private helpers ---

  private async commitStageArtifacts(stage: StageName, runId: string): Promise<void> {
    if (!this.publisher) return;
    try {
      const agentConfig = this.agentsConfig.agents[stage]!;
      const files = (agentConfig.outputs ?? []).map((o: string) => `${this.ctx.store.getDir()}/${o}`);
      const issueNumber = this.stageIssues.get(`${runId}:${stage}`);
      await this.publisher.commitStage(stage, files, issueNumber, this.ctx.store.getDir());
      const pr = this.publisher.getPR();
      if (pr && this.handler instanceof GitHubInteractionHandler) {
        this.handler.setPR(pr.number);
      }
    } catch (err) {
      this.ctx.logger.pipeline('warn', 'git-publisher:commit-failed', {
        stage, error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  private async postPreviewComment(stage: StageName, _runId: string): Promise<void> {
    if (!this.adapter || !this.publisher) return;
    const pr = this.publisher.getPR();
    if (!pr || stage !== 'ui_designer') return;
    const { owner, repo } = this.getRepoContext();
    const branch = this.publisher.getBranch() ?? '';
    if (!owner || !repo || !branch) return;
    try {
      const lines: string[] = ['## 🎨 UIDesigner — Component Preview', ''];
      const screenshotsDir = `${this.ctx.store.getDir()}/screenshots`;
      const screenshots = this.safeReadDir(screenshotsDir).filter(f => f.endsWith('.png'));
      if (screenshots.length > 0) {
        lines.push('### Screenshots', '');
        for (const file of screenshots) {
          const name = file.replace('.png', '');
          const imgUrl = `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/docs/mosaicat/screenshots/${file}`;
          lines.push(`<details><summary>${name}</summary>`, '', `![${name}](${imgUrl})`, '', '</details>', '');
        }
      }
      const previewsDir = `${this.ctx.store.getDir()}/previews`;
      const previews = this.safeReadDir(previewsDir).filter(f => f.endsWith('.html'));
      if (previews.length > 0) {
        lines.push('### Interactive Previews', '');
        for (const file of previews) {
          const name = file.replace('.html', '');
          const rawUrl = `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/docs/mosaicat/previews/${file}`;
          lines.push(`- [${name}](https://htmlpreview.github.io/?${rawUrl})`);
        }
        lines.push('');
      }
      if (fs.existsSync(`${this.ctx.store.getDir()}/gallery.html`)) {
        const rawUrl = `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/docs/mosaicat/gallery.html`;
        lines.push(`### [View Gallery](https://htmlpreview.github.io/?${rawUrl})`, '');
      }
      if (screenshots.length > 0 || previews.length > 0) {
        await this.adapter.addComment(pr.number, lines.join('\n'));
      }
    } catch (err) {
      this.ctx.logger.pipeline('warn', 'preview-comment:failed', {
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  private async createStageIssue(stage: StageName, run: PipelineRun): Promise<void> {
    if (!this.adapter) return;
    const agentConfig = this.agentsConfig.agents[stage];
    if (!agentConfig) return;
    const metrics = this.stageMetrics.get(stage);
    const manifestName = (agentConfig.outputs ?? []).find((o: string) => o.endsWith('.manifest.json'));
    const manifestSummary = manifestName ? extractManifestSummary(this.ctx.store, manifestName) : [];
    const { owner, repo } = this.getRepoContext();
    const repoSlug = owner && repo ? `${owner}/${repo}` : undefined;
    const branch = this.publisher?.getBranch() ?? undefined;
    const prNumber = this.publisher?.getPR()?.number;
    const screenshots = this.collectScreenshots();
    const params: StageIssueParams = {
      agentId: stage, agentName: agentConfig.name, agentDesc: AGENT_DESC[stage],
      taskRef: run.id, instruction: run.instruction, inputs: agentConfig.inputs ?? [],
      outputs: agentConfig.outputs ?? [], durationMs: metrics ? Date.now() - metrics.startTime : undefined,
      retryCount: run.stages[stage]?.retryCount ?? 0, clarificationQA: metrics?.clarificationQA,
      rejectionFeedback: metrics?.rejectionFeedback,
      manifestSummary: manifestSummary.length > 0 ? manifestSummary : undefined,
      screenshots: screenshots.length > 0 ? screenshots : undefined,
      commitSha: metrics?.commitSha, repoSlug, branch, prNumber,
      artifactsDir: this.ctx.store.getDir(),
    };
    const issue = await this.adapter.createIssue({
      title: buildStageIssueTitle(params), body: buildIssueBody(params),
      labels: [`agent:${stage}`, 'status:completed'],
    });
    this.stageIssues.set(`${run.id}:${stage}`, issue.number);
    this.ctx.eventBus.emit('issue:created', issue.number, stage, run.id);
  }

  private collectScreenshots(): string[] {
    const dir = `${this.ctx.store.getDir()}/screenshots`;
    try { return fs.readdirSync(dir).filter((f: string) => f.endsWith('.png')).map((f: string) => `screenshots/${f}`); }
    catch { return []; }
  }

  private safeReadDir(dir: string): string[] {
    try { return fs.readdirSync(dir); } catch { return []; }
  }
}
