import fs from 'node:fs';
import path from 'node:path';
import { getArtifactsDir } from './artifact.js';

interface PRBodyOptions {
  runId: string;
  owner: string;
  repo: string;
  branch: string;
}

function rawUrl(owner: string, repo: string, branch: string, filePath: string): string {
  return `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/${filePath}`;
}

function previewUrl(owner: string, repo: string, branch: string, filePath: string): string {
  const raw = rawUrl(owner, repo, branch, filePath);
  return `https://htmlpreview.github.io/?${raw}`;
}

export function generatePRBody(options: PRBodyOptions): string {
  const { runId, owner, repo, branch } = options;
  const sections: string[] = [];

  // Header
  sections.push(`## Mosaicat Pipeline Output\n\n**Run:** \`${runId}\``);

  // Component screenshots
  const screenshotsDir = path.join(getArtifactsDir(), 'screenshots');
  if (fs.existsSync(screenshotsDir)) {
    const screenshots = fs.readdirSync(screenshotsDir).filter((f) => f.endsWith('.png'));
    if (screenshots.length > 0) {
      const rows: string[] = ['### Component Screenshots\n'];
      for (const file of screenshots) {
        const name = path.basename(file, '.png');
        const imgUrl = rawUrl(owner, repo, branch, `${getArtifactsDir()}/screenshots/${file}`);
        rows.push(`<details><summary>${name}</summary>\n\n![${name}](${imgUrl})\n\n</details>`);
      }
      sections.push(rows.join('\n'));
    }
  }

  // Interactive preview links
  const previewsDir = path.join(getArtifactsDir(), 'previews');
  if (fs.existsSync(previewsDir)) {
    const previews = fs.readdirSync(previewsDir).filter((f) => f.endsWith('.html'));
    if (previews.length > 0) {
      const links = previews.map((f) => {
        const name = path.basename(f, '.html');
        const url = previewUrl(owner, repo, branch, `${getArtifactsDir()}/previews/${f}`);
        return `- [${name}](${url})`;
      });
      sections.push(`### Interactive Previews\n\n${links.join('\n')}`);
    }
  }

  // Gallery link
  if (fs.existsSync(path.join(getArtifactsDir(), 'gallery.html'))) {
    const galleryUrl = previewUrl(owner, repo, branch, `${getArtifactsDir()}/gallery.html`);
    sections.push(`### Gallery\n\n[View all components](${galleryUrl})`);
  }

  // Validation status
  const validationPath = path.join(getArtifactsDir(), 'validation-report.md');
  if (fs.existsSync(validationPath)) {
    const report = fs.readFileSync(validationPath, 'utf-8');
    const statusMatch = report.match(/- Status: (PASS|FAIL)/);
    const status = statusMatch ? statusMatch[1] : 'UNKNOWN';
    const icon = status === 'PASS' ? ':white_check_mark:' : ':x:';
    sections.push(`### Validation\n\n${icon} **${status}**`);
  }

  sections.push('\n---\n_Generated by [Mosaicat](https://github.com/ZB-ur/mosaicat) pipeline_');

  return sections.join('\n\n');
}
