import fs from 'node:fs';
import path from 'node:path';
import type { StageName } from './types.js';
import type { LLMUsage } from './llm-provider.js';
import { STAGE_ORDER } from './types.js';

const ARTIFACTS_DIR = '.mosaic/artifacts';

interface PRBodyOptions {
  runId: string;
  owner: string;
  repo: string;
  branch: string;
  stageUsage?: Map<StageName, LLMUsage>;
}

function formatTokens(n: number): string {
  if (n < 1000) return `${n}`;
  return `${(n / 1000).toFixed(1)}k`;
}

function rawUrl(owner: string, repo: string, branch: string, filePath: string): string {
  return `https://raw.githubusercontent.com/${owner}/${repo}/${branch}/${filePath}`;
}

function previewUrl(owner: string, repo: string, branch: string, filePath: string): string {
  const raw = rawUrl(owner, repo, branch, filePath);
  return `https://htmlpreview.github.io/?${raw}`;
}

export function generatePRBody(options: PRBodyOptions): string {
  const { runId, owner, repo, branch, stageUsage } = options;
  const sections: string[] = [];

  // Header
  sections.push(`## Mosaicat Pipeline Output\n\n**Run:** \`${runId}\``);

  // Pipeline usage summary
  if (stageUsage && stageUsage.size > 0) {
    const rows: string[] = ['| Stage | In Tokens | Out Tokens | Cost |', '|-------|-----------|------------|------|'];
    let totalIn = 0, totalOut = 0, totalCost = 0;

    for (const stage of STAGE_ORDER) {
      const usage = stageUsage.get(stage);
      if (!usage) continue;
      totalIn += usage.input_tokens;
      totalOut += usage.output_tokens;
      const cost = usage.cost_usd ?? 0;
      totalCost += cost;
      rows.push(`| ${stage} | ${formatTokens(usage.input_tokens)} | ${formatTokens(usage.output_tokens)} | $${cost.toFixed(2)} |`);
    }

    rows.push(`| **Total** | **${formatTokens(totalIn)}** | **${formatTokens(totalOut)}** | **$${totalCost.toFixed(2)}** |`);
    sections.push(`### Token Usage\n\n${rows.join('\n')}`);
  }

  // Component screenshots
  const screenshotsDir = path.join(ARTIFACTS_DIR, 'screenshots');
  if (fs.existsSync(screenshotsDir)) {
    const screenshots = fs.readdirSync(screenshotsDir).filter((f) => f.endsWith('.png'));
    if (screenshots.length > 0) {
      const rows: string[] = ['### Component Screenshots\n'];
      for (const file of screenshots) {
        const name = path.basename(file, '.png');
        const imgUrl = rawUrl(owner, repo, branch, `${ARTIFACTS_DIR}/screenshots/${file}`);
        rows.push(`<details><summary>${name}</summary>\n\n![${name}](${imgUrl})\n\n</details>`);
      }
      sections.push(rows.join('\n'));
    }
  }

  // Interactive preview links
  const previewsDir = path.join(ARTIFACTS_DIR, 'previews');
  if (fs.existsSync(previewsDir)) {
    const previews = fs.readdirSync(previewsDir).filter((f) => f.endsWith('.html'));
    if (previews.length > 0) {
      const links = previews.map((f) => {
        const name = path.basename(f, '.html');
        const url = previewUrl(owner, repo, branch, `${ARTIFACTS_DIR}/previews/${f}`);
        return `- [${name}](${url})`;
      });
      sections.push(`### Interactive Previews\n\n${links.join('\n')}`);
    }
  }

  // Gallery link
  if (fs.existsSync(path.join(ARTIFACTS_DIR, 'gallery.html'))) {
    const galleryUrl = previewUrl(owner, repo, branch, `${ARTIFACTS_DIR}/gallery.html`);
    sections.push(`### Gallery\n\n[View all components](${galleryUrl})`);
  }

  // Validation status
  const validationPath = path.join(ARTIFACTS_DIR, 'validation-report.md');
  if (fs.existsSync(validationPath)) {
    const report = fs.readFileSync(validationPath, 'utf-8');
    const statusMatch = report.match(/- Status: (PASS|FAIL)/);
    const status = statusMatch ? statusMatch[1] : 'UNKNOWN';
    const icon = status === 'PASS' ? ':white_check_mark:' : ':x:';
    sections.push(`### Validation\n\n${icon} **${status}**`);
  }

  sections.push('\n---\n_Generated by [Mosaicat](https://github.com/ZB-ur/mosaicat) pipeline_');

  return sections.join('\n\n');
}
