import type { PipelineConfig } from './types.js';

export enum TrustLevel {
  Initiator = 0,
  Orchestrator = 1,
  Agent = 2,
  External = 3,
}

export interface SecurityConfig {
  initiatorLogin: string;
  rejectPolicy: 'silent' | 'error';
}

export function loadSecurityConfig(
  pipelineConfig: PipelineConfig,
  initiatorLogin?: string,
): SecurityConfig {
  return {
    initiatorLogin:
      initiatorLogin ??
      pipelineConfig.security.initiator ??
      '',
    rejectPolicy: (pipelineConfig.security.reject_policy as 'silent' | 'error') ?? 'silent',
  };
}

export function isTrustedActor(login: string, config: SecurityConfig): boolean {
  if (!config.initiatorLogin) return false;
  return login === config.initiatorLogin;
}

export function assertTrustedActor(login: string, config: SecurityConfig): void {
  if (!isTrustedActor(login, config)) {
    throw new Error(`Untrusted actor: ${login} (expected: ${config.initiatorLogin})`);
  }
}

export function buildIssueBody(params: {
  agentId: string;
  taskRef: string;
  outputs: string[];
}): string {
  const outputsList = params.outputs.map((o) => `- \`${o}\``).join('\n');
  return `## Pipeline Stage Report

**Agent:** ${params.agentId}
**Task:** ${params.taskRef}

### Outputs
${outputsList}

---
_Generated by Mosaicat pipeline_`;
}
