import type { PipelineConfig } from './types.js';

export enum TrustLevel {
  Initiator = 0,
  Orchestrator = 1,
  Agent = 2,
  External = 3,
}

export interface SecurityConfig {
  initiatorLogin: string;
  rejectPolicy: 'silent' | 'error';
}

export function loadSecurityConfig(pipelineConfig: PipelineConfig): SecurityConfig {
  const initiatorLogin =
    process.env.MOSAIC_INITIATOR_LOGIN ?? pipelineConfig.security.initiator ?? '';
  return {
    initiatorLogin,
    rejectPolicy: (pipelineConfig.security.reject_policy as 'silent' | 'error') ?? 'silent',
  };
}

export function isTrustedActor(login: string, config: SecurityConfig): boolean {
  if (!config.initiatorLogin) return false;
  return login === config.initiatorLogin;
}

export function assertTrustedActor(login: string, config: SecurityConfig): void {
  if (!isTrustedActor(login, config)) {
    throw new Error(`Untrusted actor: ${login} (expected: ${config.initiatorLogin})`);
  }
}

export function buildIssueBody(params: {
  agentId: string;
  taskRef: string;
  outputs: string[];
}): string {
  const outputsList = params.outputs.map((o) => `- \`${o}\``).join('\n');
  return `## Pipeline Stage Report

**Agent:** ${params.agentId}
**Task:** ${params.taskRef}

### Outputs
${outputsList}

---
_Generated by Mosaicat pipeline_`;
}

export function validateGitHubEnv(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!process.env.GITHUB_TOKEN) {
    errors.push('GITHUB_TOKEN is not set');
  }
  if (!process.env.MOSAIC_GITHUB_REPO) {
    errors.push('MOSAIC_GITHUB_REPO is not set');
  } else {
    const parts = process.env.MOSAIC_GITHUB_REPO.split('/');
    if (parts.length !== 2 || !parts[0] || !parts[1]) {
      errors.push('MOSAIC_GITHUB_REPO must be in format: owner/repo');
    }
  }
  if (!process.env.MOSAIC_INITIATOR_LOGIN) {
    errors.push('MOSAIC_INITIATOR_LOGIN is not set');
  }

  return { valid: errors.length === 0, errors };
}
