import type { PipelineConfig } from './types.js';

export enum TrustLevel {
  Initiator = 0,
  Orchestrator = 1,
  Agent = 2,
  External = 3,
}

export interface SecurityConfig {
  initiatorLogin: string;
  rejectPolicy: 'silent' | 'error';
}

export interface AuthOverrides {
  initiatorLogin?: string;
}

export function loadSecurityConfig(
  pipelineConfig: PipelineConfig,
  authOverrides?: AuthOverrides,
): SecurityConfig {
  const initiatorLogin =
    authOverrides?.initiatorLogin ??
    process.env.MOSAIC_INITIATOR_LOGIN ??
    pipelineConfig.security.initiator ??
    '';
  return {
    initiatorLogin,
    rejectPolicy: (pipelineConfig.security.reject_policy as 'silent' | 'error') ?? 'silent',
  };
}

export function isTrustedActor(login: string, config: SecurityConfig): boolean {
  if (!config.initiatorLogin) return false;
  return login === config.initiatorLogin;
}

export function assertTrustedActor(login: string, config: SecurityConfig): void {
  if (!isTrustedActor(login, config)) {
    throw new Error(`Untrusted actor: ${login} (expected: ${config.initiatorLogin})`);
  }
}

export function buildIssueBody(params: {
  agentId: string;
  taskRef: string;
  outputs: string[];
}): string {
  const outputsList = params.outputs.map((o) => `- \`${o}\``).join('\n');
  return `## Pipeline Stage Report

**Agent:** ${params.agentId}
**Task:** ${params.taskRef}

### Outputs
${outputsList}

---
_Generated by Mosaicat pipeline_`;
}

/** Legacy validation — checks all 3 env vars for personal token mode */
export function validateGitHubEnv(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!process.env.GITHUB_TOKEN) {
    errors.push('GITHUB_TOKEN is not set');
  }
  if (!process.env.MOSAIC_GITHUB_REPO) {
    errors.push('MOSAIC_GITHUB_REPO is not set');
  } else {
    const parts = process.env.MOSAIC_GITHUB_REPO.split('/');
    if (parts.length !== 2 || !parts[0] || !parts[1]) {
      errors.push('MOSAIC_GITHUB_REPO must be in format: owner/repo');
    }
  }
  if (!process.env.MOSAIC_INITIATOR_LOGIN) {
    errors.push('MOSAIC_INITIATOR_LOGIN is not set');
  }

  return { valid: errors.length === 0, errors };
}

/**
 * Dual-mode validation: returns 'app' if App mode is available,
 * 'token' if legacy env vars are set, or 'none' with errors.
 */
export function detectGitHubAuthMode(): { mode: 'app' | 'token' | 'none'; errors: string[] } {
  // Legacy mode: GITHUB_TOKEN is set
  if (process.env.GITHUB_TOKEN) {
    const envCheck = validateGitHubEnv();
    return envCheck.valid ? { mode: 'token', errors: [] } : { mode: 'none', errors: envCheck.errors };
  }

  // App mode: checked at runtime via resolveGitHubAuth()
  // We can't fully validate here (needs async backend call),
  // so just signal that App mode should be attempted
  return { mode: 'app', errors: [] };
}
